# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Regen/Desktop/buptriscv/buptriscv.srcs/sources_1/ip/dmemblock/dmemblock.xci
# IP: The module: 'dmemblock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/dmemblock/dmemblock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmemblock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Regen/Desktop/buptriscv/buptriscv.srcs/sources_1/ip/dmemblock/dmemblock.xci
# IP: The module: 'dmemblock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/dmemblock/dmemblock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmemblock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
