# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Regen/Desktop/buptriscv/buptriscv.srcs/sources_1/ip/clockgen/clockgen.xci
# IP: The module: 'clockgen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/clockgen/clockgen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockgen'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/clockgen/clockgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/clockgen/clockgen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Regen/Desktop/buptriscv/buptriscv.srcs/sources_1/ip/clockgen/clockgen.xci
# IP: The module: 'clockgen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/clockgen/clockgen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/clockgen/clockgen.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Regen/Desktop/buptriscv/buptriscv.gen/sources_1/ip/clockgen/clockgen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockgen'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
